#!/bin/bash
echo "════════════════════════════════════════════════════"
echo "  📥 HƯỚNG DẪN TẢI QUIZ-GAME VỀ MÁY"
echo "════════════════════════════════════════════════════"
echo ""
echo "File đã được chuẩn bị tại: /workspace/quiz-game.zip"
echo "Kích thước: $(du -h /workspace/quiz-game.zip | cut -f1)"
echo ""
echo "════════════════════════════════════════════════════"
echo "CÁCH 1: Tải qua Cursor Terminal"
echo "════════════════════════════════════════════════════"
echo ""
echo "1. Mở Terminal trong Cursor (Ctrl + \` hoặc Cmd + \`)"
echo "2. Chạy lệnh sau để copy về Desktop:"
echo ""
echo "   cp /workspace/quiz-game.zip ~/Desktop/"
echo ""
echo "   Hoặc về Downloads:"
echo "   cp /workspace/quiz-game.zip ~/Downloads/"
echo ""
echo "════════════════════════════════════════════════════"
echo "CÁCH 2: Xem nội dung trực tiếp"
echo "════════════════════════════════════════════════════"
echo ""
echo "Danh sách files trong quiz-game:"
echo ""
find /workspace/quiz-game -type f | sort
echo ""
echo "════════════════════════════════════════════════════"
echo "CÁCH 3: Clone từ GitHub (sau khi push)"
echo "════════════════════════════════════════════════════"
echo ""
echo "Sau khi tôi push lên GitHub, bạn chạy:"
echo "git clone https://github.com/hongninh/quiz.git"
echo ""
echo "════════════════════════════════════════════════════"
