/**
 * LOCAL DATA INPUT
 * Chứa dữ liệu quiz - có thể thay thế bằng data từ backend
 * File này được load trước local-quiz-complete.js
 */

// Khai báo biến global chứa quiz data
window.quizData = {
    "main_game_id": "complete_quiz_2025",
    "main_title": "Quiz Hoàn Chỉnh - 12 Câu Hỏi Đa Dạng",
    "main_description": "Bộ câu hỏi bao gồm tất cả các dạng: MCQ, Multi, Image, Hotspot, Order, Pair, Drag-Drop",
    "main_project_id": "proj_hazard_2025",
    "main_game_version": "1.0.0",
    "main_author": "Quiz Team",
    "main_age_array": [8, 9, 10, 11],
    "main_grade": "Primary",
    "main_total_questions": 12,
    "main_total_max_points": 200,
    "main_max_time_per_game_ms": 300000,
    "main_language": "vi",
    "main_theme": "safety_traffic",
    "main_difficulty_level": "mixed",
    "main_show_correct_answer_after_each_quiz": true,
    "main_shuffle_questions_order": false,
    "main_default_hint_allow": true,
    "main_default_hint_penalty_percent": 20,
    "main_feedback_mode": "detailed_explanation",
    "main_pass_threshold_percent": 70,
    "main_status": "published",
    "EachQuiz": [
        {
            "qn": 1,
            "qid": "traffic_001",
            "qtype": "hotspot",
            "qtxt": "Hãy bấm vào vị trí có vạch kẻ dành cho người đi bộ",
            "pmax": 10,
            "tmax": 30000,
            "diff": "easy",
            "fq": true,
            "lq": false,
            "opt_array": null,
            "sol_json": { "x": 400, "y": 300, "radius": 80 },
            "expl": "Vạch kẻ trắng ngang đường là nơi an toàn để học sinh sang đường.",
            "tag_array": ["crosswalk", "pedestrian"],
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1758463771/68633251_tr3nqn.jpg"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_only",
            "media_placement": "background",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Tìm dấu hiệu an toàn nhất để qua đường.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": false,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 2,
            "qid": "traffic_002",
            "qtype": "multi",
            "qtxt": "Trong các lựa chọn sau, đâu là phương tiện giao thông an toàn, hợp pháp cho học sinh tiểu học?",
            "pmax": 15,
            "tmax": 40000,
            "diff": "medium",
            "fq": false,
            "lq": false,
            "opt_array": ["Xe đạp", "Xe máy", "Ô tô đi cùng bố mẹ", "Xe buýt trường học", "Xe tải"],
            "sol_array": ["Xe đạp", "Ô tô đi cùng bố mẹ", "Xe buýt trường học"],
            "expl": "Học sinh tiểu học chỉ nên đi bộ, đi xe đạp hoặc được đưa đón bằng xe buýt/ô tô cùng người lớn.",
            "tag_array": ["vehicle", "safe"],
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1758463465/important_road_safety_rules_to_teach_your_children_illustration.jpg_vk7gty.webp"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "text_only",
            "media_placement": "above",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Luật giao thông quy định độ tuổi và giấy phép lái xe cho từng loại phương tiện.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": true,
            "display": "hide",
            "display_correct_answer": "y"
        },
        {
            "qn": 3,
            "qid": "traffic_003",
            "qtype": "mcq",
            "qtxt": "Đèn tín hiệu giao thông màu đỏ nghĩa là gì?",
            "pmax": 10,
            "tmax": 20000,
            "diff": "easy",
            "fq": false,
            "lq": false,
            "opt_array": ["Dừng lại", "Đi chậm", "Được đi tiếp", "Rẽ phải"],
            "sol_array": "Dừng lại",
            "expl": "Đèn đỏ nghĩa là mọi phương tiện và người đi bộ phải dừng lại.",
            "tag_array": ["traffic_light"],
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1758463334/Teach-Road-Safety-to-Kids-1_kibxvw.png"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "text_only",
            "media_placement": "above",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": false,
            "hint_penalty_percent": 20,
            "hint_content_text": "Đây là kiến thức cơ bản nhất về luật giao thông.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": true,
            "display": "hide",
            "display_correct_answer": "y"
        },
        {
            "qn": 4,
            "qid": "traffic_004",
            "qtype": "order",
            "qtxt": "Sắp xếp đúng thứ tự các bước khi qua đường tại ngã tư có đèn tín hiệu",
            "pmax": 20,
            "tmax": 50000,
            "diff": "hard",
            "fq": false,
            "lq": false,
            "opt_array": ["Nhìn trái – nhìn phải", "Chờ đèn xanh cho người đi bộ", "Đi nhanh qua vạch kẻ", "Không dừng giữa đường"],
            "sol_array": ["Chờ đèn xanh cho người đi bộ", "Nhìn trái – nhìn phải", "Đi nhanh qua vạch kẻ", "Không dừng giữa đường"],
            "expl": "Trẻ em cần tuân thủ đủ 4 bước: chờ tín hiệu, quan sát an toàn, và đi qua dứt khoát.",
            "tag_array": ["order", "crossing"],
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1759660871/88745398_road-safety_qjetaw.jpg"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "text_only",
            "media_placement": "above",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Điều đầu tiên luôn là phải tuân theo tín hiệu, sau đó mới đến quan sát.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": false,
            "display": "hide",
            "display_correct_answer": "y"
        },
        {
            "qn": 5,
            "qid": "traffic_005",
            "qtype": "image_pair",
            "qtxt": "Ghép cặp hành động an toàn và nguy hiểm tương ứng",
            "pmax": 25,
            "tmax": 60000,
            "diff": "hard",
            "fq": false,
            "lq": false,
            "opt_array": null,
            "sol_array": [[0, 0], [1, 1], [2, 2]],
            "expl": "Luôn ghép hành động đúng với hành động sai tương ứng.",
            "tag_array": ["image_pair", "safe_vs_danger"],
            "image_json": [
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662280/89039832_children_tw6zrn.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759661153/87498090_a-car-bumping-the-traffic-cones_pk60x0.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662493/88589066_children_1_j24kzx.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662282/89505552_children_snzywa.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662851/36960374_children_xterrv.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662490/87614454_children_rkfqo3.jpg"
            ],
            "image_total_number": 6,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_only",
            "media_placement": "side_by_side",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Ghép hình ảnh 1 với 4, 2 với 5, 3 với 6.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": true,
            "display": "hide",
            "display_correct_answer": "y"
        },
        {
            "qn": 6,
            "qid": "traffic_006",
            "qtype": "image_mcq",
            "qtxt": "Thiết bị bảo hộ nào là BẮT BUỘC khi đi xe đạp trên đường?",
            "pmax": 15,
            "tmax": 30000,
            "diff": "medium",
            "fq": false,
            "lq": false,
            "opt_array": [
                { "text": "Mũ bảo hiểm xe đạp", "image": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=400&h=300&fit=crop" },
                { "text": "Mũ thời trang", "image": "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=300&fit=crop" },
                { "text": "Nón lá", "image": "https://images.unsplash.com/photo-1578922746064-031a8c0cb677?w=400&h=300&fit=crop" },
                { "text": "Không cần đội gì", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop" }
            ],
            "sol_array": 0,
            "expl": "Mũ bảo hiểm xe đạp là thiết bị bảo hộ quan trọng giúp bảo vệ đầu khi té ngã.",
            "tag_array": ["helmet", "bicycle", "safety"],
            "image_json": null,
            "image_total_number": 0,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_text",
            "media_placement": "inline",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Tìm thiết bị được thiết kế chuyên dụng cho xe đạp.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": false,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 7,
            "qid": "traffic_007",
            "qtype": "image_mcq",
            "qtxt": "Chọn biển báo CẤM ĐI NGƯỢC CHIỀU",
            "pmax": 10,
            "tmax": 25000,
            "diff": "easy",
            "fq": false,
            "lq": false,
            "opt_array": [
                { "text": "Biển cấm đi ngược chiều", "image": "https://images.unsplash.com/photo-1544919982-b61976f0ba43?w=400&h=300&fit=crop" },
                { "text": "Biển dừng lại", "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=300&fit=crop" },
                { "text": "Biển ưu tiên", "image": "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=400&h=300&fit=crop" },
                { "text": "Biển chỉ đường", "image": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=300&fit=crop" }
            ],
            "sol_array": 0,
            "expl": "Biển cấm đi ngược chiều có hình tròn đỏ với vạch trắng ngang.",
            "tag_array": ["traffic_sign", "prohibition"],
            "image_json": null,
            "image_total_number": 0,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_text",
            "media_placement": "inline",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 15,
            "hint_content_text": "Biển cấm có hình tròn với viền đỏ.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": false,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 8,
            "qid": "traffic_008",
            "qtype": "image_multi",
            "qtxt": "Chọn TẤT CẢ các biển báo NGUY HIỂM",
            "pmax": 15,
            "tmax": 35000,
            "diff": "medium",
            "fq": false,
            "lq": false,
            "opt_array": [
                { "text": "Cẩn thận công trình", "image": "https://images.unsplash.com/photo-1544919982-b61976f0ba43?w=300&h=200&fit=crop" },
                { "text": "Nguy hiểm điện cao thế", "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop" },
                { "text": "Chỉ dẫn hướng đi", "image": "https://images.unsplash.com/photo-1542831371-d531d36971e6?w=300&h=200&fit=crop" },
                { "text": "Ngã tư nguy hiểm", "image": "https://images.unsplash.com/photo-1449247666642-264389f5f5b1?w=300&h=200&fit=crop" }
            ],
            "sol_array": [0, 1, 3],
            "expl": "Biển nguy hiểm thường có màu vàng hình tam giác để cảnh báo.",
            "tag_array": ["warning_sign", "danger"],
            "image_json": null,
            "image_total_number": 0,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_text",
            "media_placement": "inline",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Biển nguy hiểm có hình tam giác màu vàng với viền đỏ.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": true,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 9,
            "qid": "safety_009",
            "qtype": "drag_drop",
            "qtxt": "Kéo thả các hình ảnh vào cột AN TOÀN hoặc NGUY CƠ",
            "pmax": 20,
            "tmax": 45000,
            "diff": "medium",
            "fq": false,
            "lq": false,
            "opt_array": null,
            "drag_items": [
                { "id": "item_1", "label": "Mặc đồ bảo hộ", "image": "https://images.unsplash.com/photo-1572107248692-1d32d1f5fc3a?w=200&h=150&fit=crop", "correct_zone": "safe" },
                { "id": "item_2", "label": "Hút thuốc", "image": "https://images.unsplash.com/photo-1605671919743-c3cd293be5e7?w=200&h=150&fit=crop", "correct_zone": "danger" },
                { "id": "item_3", "label": "Đeo kính bảo hộ", "image": "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=200&h=150&fit=crop", "correct_zone": "safe" },
                { "id": "item_4", "label": "Chạy trong nhà máy", "image": "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=200&h=150&fit=crop", "correct_zone": "danger" },
                { "id": "item_5", "label": "Rửa tay đúng cách", "image": "https://images.unsplash.com/photo-1584555613497-9ecf9dd06f68?w=200&h=150&fit=crop", "correct_zone": "safe" },
                { "id": "item_6", "label": "Dùng điện thoại khi vận hành", "image": "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=200&h=150&fit=crop", "correct_zone": "danger" }
            ],
            "sol_array": null,
            "expl": "Phân biệt rõ hành động an toàn và nguy hiểm tại nơi làm việc.",
            "tag_array": ["drag_drop", "workplace_safety"],
            "image_json": null,
            "image_total_number": 6,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_text",
            "media_placement": "inline",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Quan sát kỹ từng hành động và đánh giá mức độ an toàn.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": true,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 10,
            "qid": "safety_010",
            "qtype": "multi_hotspot",
            "qtxt": "Click vào TẤT CẢ các điểm NGUY HIỂM trên hình ảnh công trường",
            "pmax": 20,
            "tmax": 60000,
            "diff": "hard",
            "fq": false,
            "lq": false,
            "opt_array": null,
            "hotspot_array": [
                { "id": "spot_1", "x": 25, "y": 30 },
                { "id": "spot_2", "x": 50, "y": 40 },
                { "id": "spot_3", "x": 75, "y": 35 },
                { "id": "spot_4", "x": 30, "y": 70 },
                { "id": "spot_5", "x": 65, "y": 75 }
            ],
            "sol_array": ["spot_1", "spot_3", "spot_5"],
            "expl": "Cần nhận biết được các điểm nguy hiểm để tránh tai nạn lao động.",
            "tag_array": ["multi_hotspot", "workplace_hazard"],
            "image_json": ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_only",
            "media_placement": "background",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Tìm các vị trí không có biện pháp bảo vệ hoặc có nguy cơ rơi, va chạm.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": false,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 11,
            "qid": "safety_011",
            "qtype": "image_mcq",
            "qtxt": "Thiết bị bảo hộ nào là BẮT BUỘC khi làm việc ở công trường xây dựng?",
            "pmax": 10,
            "tmax": 25000,
            "diff": "easy",
            "fq": false,
            "lq": false,
            "opt_array": [
                { "text": "Mũ bảo hiểm", "image": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=400&h=300&fit=crop" },
                { "text": "Nón lá", "image": "https://images.unsplash.com/photo-1578922746064-031a8c0cb677?w=400&h=300&fit=crop" },
                { "text": "Mũ thời trang", "image": "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=300&fit=crop" },
                { "text": "Không cần đội gì", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop" }
            ],
            "sol_array": 0,
            "expl": "Mũ bảo hiểm là thiết bị bảo hộ bắt buộc tại mọi công trường xây dựng theo quy định an toàn lao động.",
            "tag_array": ["helmet", "construction", "ppe"],
            "image_json": null,
            "image_total_number": 0,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_text",
            "media_placement": "inline",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 15,
            "hint_content_text": "Tìm thiết bị được thiết kế để bảo vệ đầu khỏi va đập.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": false,
            "display": "show",
            "display_correct_answer": "y"
        },
        {
            "qn": 12,
            "qid": "safety_012",
            "qtype": "image_multi",
            "qtxt": "Chọn TẤT CẢ các thiết bị bảo hộ cá nhân cần thiết khi làm việc với hóa chất",
            "pmax": 15,
            "tmax": 40000,
            "diff": "medium",
            "fq": false,
            "lq": true,
            "opt_array": [
                { "text": "Găng tay chống hóa chất", "image": "https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&h=300&fit=crop" },
                { "text": "Kính bảo hộ", "image": "https://images.unsplash.com/photo-1577803645773-f96470509666?w=400&h=300&fit=crop" },
                { "text": "Quần áo thời trang", "image": "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&h=300&fit=crop" },
                { "text": "Khẩu trang phòng độc", "image": "https://images.unsplash.com/photo-1584515933487-779824d29309?w=400&h=300&fit=crop" }
            ],
            "sol_array": [0, 1, 3],
            "expl": "Cần đầy đủ găng tay chống hóa chất, kính bảo hộ và khẩu trang phòng độc khi làm việc với hóa chất.",
            "tag_array": ["ppe", "chemical_safety", "multi_choice"],
            "image_json": null,
            "image_total_number": 0,
            "audio_json": null,
            "video_json": null,
            "opt_fmt": "image_text",
            "media_placement": "inline",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "project_id": "proj_hazard_2025",
            "age": "8-11",
            "grade": "primary",
            "lang": "vi",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Hóa chất có thể gây hại qua da, mắt và đường hô hấp.",
            "hint_content_media": null,
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "shuf": true,
            "display": "show",
            "display_correct_answer": "y"
        }
    ]
};

console.log('✅ Quiz data loaded:', window.quizData.main_title);
