/**
 * LOCAL DATA INPUT
 * Chứa dữ liệu quiz - có thể thay thế bằng data từ backend
 * File này được load trước local-quiz-complete.js
 */

// Khai báo biến global chứa quiz data
// Cấu trúc chuẩn theo backend procfu.com
window.quizData = {
    "main_game_id": "traffic_safety_primary_2025",
    "main_title": "An Toàn Giao Thông: Thử Thách Cho Học Sinh Tiểu Học",
    "main_description": "Bộ câu hỏi kiểm tra kiến thức và kỹ năng an toàn giao thông đường bộ cơ bản cho học sinh tiểu học (8-11 tuổi).",
    "main_project_id": "proj_hazard_2025",
    "main_game_version": "1.0.0",
    "main_author": "Traffic Safety Team",
    "main_age_array": [8, 9, 10, 11],
    "main_grade": "Primary",
    "main_total_questions": 5,
    "main_total_max_points": 80,
    "main_max_time_per_game_ms": 200000,
    "main_language": "vi",
    "main_theme": "traffic_safety",
    "main_difficulty_level": "mixed",
    "main_show_correct_answer_after_each_quiz": true,
    "main_shuffle_questions_order": false,
    "main_default_hint_allow": true,
    "main_default_hint_penalty_percent": 20,
    "main_feedback_mode": "detailed_explanation",
    "main_pass_threshold_percent": 70,
    "main_media_assets_root_url": "https://res.cloudinary.com/dcuqbylaa/image/upload/v1760225296/hq720_fylduj.jpg",
    "main_status": "published",
    "EachQuiz": [
        {
            "qn": 1,
            "qid": "traffic_001",
            "fq": true,
            "lq": false,
            "tmax": 30000,
            "pmax": 10,
            "diff": "easy",
            "qtype": "hotspot",
            "qtxt": "Hãy bấm vào vị trí có vạch kẻ dành cho người đi bộ.",
            "age": "8-11",
            "grade": "primary",
            "project_id": "proj_hazard_2025",
            "display": "show",
            "display_correct_answer": "y",
            "opt_array": null,
            "sol_json": {
                "x": 200,
                "y": 250,
                "radius": 40
            },
            "expl": "Vạch kẻ trắng ngang đường là nơi an toàn để học sinh sang đường.",
            "tag_array": ["crosswalk", "pedestrian"],
            "lang": "vi",
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1758463771/68633251_tr3nqn.jpg"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "shuf": false,
            "opt_fmt": "image_only",
            "media_placement": "background",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Tìm dấu hiệu an toàn nhất để qua đường.",
            "hint_content_media": null
        },
        {
            "qn": 2,
            "qid": "traffic_002",
            "fq": false,
            "lq": false,
            "tmax": 40000,
            "pmax": 15,
            "diff": "medium",
            "qtype": "multi",
            "qtxt": "Trong các lựa chọn sau, đâu là phương tiện giao thông an toàn, hợp pháp cho học sinh tiểu học?",
            "age": "8-11",
            "grade": "primary",
            "project_id": "proj_hazard_2025",
            "display": "hide",
            "display_correct_answer": "y",
            "opt_array": [
                "Xe đạp",
                "Xe máy",
                "Ô tô đi cùng bố mẹ",
                "Xe buýt trường học",
                "Xe tải"
            ],
            "sol_array": [
                "Xe đạp",
                "Ô tô đi cùng bố mẹ",
                "Xe buýt trường học"
            ],
            "expl": "Học sinh tiểu học chỉ nên đi bộ, đi xe đạp hoặc được đưa đón bằng xe buýt/ô tô cùng người lớn.",
            "tag_array": ["vehicle", "safe"],
            "lang": "vi",
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1758463465/important_road_safety_rules_to_teach_your_children_illustration.jpg_vk7gty.webp"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "shuf": true,
            "opt_fmt": "text_only",
            "media_placement": "above",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Luật giao thông quy định độ tuổi và giấy phép lái xe cho từng loại phương tiện.",
            "hint_content_media": null
        },
        {
            "qn": 3,
            "qid": "traffic_003",
            "fq": false,
            "lq": false,
            "tmax": 20000,
            "pmax": 10,
            "diff": "easy",
            "qtype": "mcq",
            "qtxt": "Đèn tín hiệu giao thông màu đỏ nghĩa là gì?",
            "age": "8-11",
            "grade": "primary",
            "project_id": "proj_hazard_2025",
            "display": "hide",
            "display_correct_answer": "y",
            "opt_array": [
                "Dừng lại",
                "Đi chậm",
                "Được đi tiếp",
                "Rẽ phải"
            ],
            "sol_array": "Dừng lại",
            "expl": "Đèn đỏ nghĩa là mọi phương tiện và người đi bộ phải dừng lại.",
            "tag_array": ["traffic_light"],
            "lang": "vi",
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1758463334/Teach-Road-Safety-to-Kids-1_kibxvw.png"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "shuf": true,
            "opt_fmt": "text_only",
            "media_placement": "above",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": false,
            "hint_penalty_percent": 20,
            "hint_content_text": "Đây là kiến thức cơ bản nhất về luật giao thông.",
            "hint_content_media": null
        },
        {
            "qn": 4,
            "qid": "traffic_004",
            "fq": false,
            "lq": false,
            "tmax": 50000,
            "pmax": 20,
            "diff": "hard",
            "qtype": "order",
            "qtxt": "Sắp xếp đúng thứ tự các bước khi qua đường tại ngã tư có đèn tín hiệu.",
            "age": "8-11",
            "grade": "primary",
            "project_id": "proj_hazard_2025",
            "display": "hide",
            "display_correct_answer": "y",
            "opt_array": [
                "Nhìn trái – nhìn phải",
                "Chờ đèn xanh cho người đi bộ",
                "Đi nhanh qua vạch kẻ",
                "Không dừng giữa đường"
            ],
            "sol_array": [
                "Chờ đèn xanh cho người đi bộ",
                "Nhìn trái – nhìn phải",
                "Đi nhanh qua vạch kẻ",
                "Không dừng giữa đường"
            ],
            "expl": "Trẻ em cần tuân thủ đủ 4 bước: chờ tín hiệu, quan sát an toàn, và đi qua dứt khoát.",
            "tag_array": ["order", "crossing"],
            "lang": "vi",
            "image_json": ["https://res.cloudinary.com/dcuqbylaa/image/upload/v1759660871/88745398_road-safety_qjetaw.jpg"],
            "image_total_number": 1,
            "audio_json": null,
            "video_json": null,
            "shuf": false,
            "opt_fmt": "text_only",
            "media_placement": "above",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Điều đầu tiên luôn là phải tuân theo tín hiệu, sau đó mới đến quan sát.",
            "hint_content_media": "https://example.com/quiz/crossing_video_hint.mp4"
        },
        {
            "qn": 5,
            "qid": "traffic_005",
            "fq": false,
            "lq": true,
            "tmax": 60000,
            "pmax": 25,
            "diff": "hard",
            "qtype": "image_pair",
            "qtxt": "Ghép cặp hành động an toàn và nguy hiểm tương ứng.",
            "age": "8-11",
            "grade": "primary",
            "project_id": "proj_hazard_2025",
            "display": "hide",
            "display_correct_answer": "y",
            "opt_array": null,
            "sol_array": [[0, 0], [1, 1], [2, 2]],
            "expl": "Luôn ghép hành động đúng với hành động sai tương ứng.",
            "tag_array": ["image_pair", "safe_vs_danger"],
            "lang": "vi",
            "image_json": [
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662280/89039832_children_tw6zrn.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759661153/87498090_a-car-bumping-the-traffic-cones_pk60x0.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662493/88589066_children_1_j24kzx.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662282/89505552_children_snzywa.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662851/36960374_children_xterrv.jpg",
                "https://res.cloudinary.com/dcuqbylaa/image/upload/v1759662490/87614454_children_rkfqo3.jpg"
            ],
            "image_total_number": 6,
            "audio_json": null,
            "video_json": null,
            "shuf": true,
            "opt_fmt": "image_only",
            "media_placement": "side_by_side",
            "expl_fmt": "plain",
            "author_id": "admin_001",
            "created_at": "2025-01-10T10:00:00Z",
            "updated_at": "2025-01-10T10:00:00Z",
            "status": "active",
            "version": "1.0",
            "is_private": false,
            "penalty_points": 0,
            "min_points": 0,
            "speed_bonus_eligible": true,
            "hint_allow": true,
            "hint_penalty_percent": 20,
            "hint_content_text": "Ghép hình ảnh 1 với 4, 2 với 5, 3 với 6.",
            "hint_content_media": null
        }
    ]
};

console.log('✅ Quiz data loaded:', window.quizData.main_title);
console.log('📊 Total questions:', window.quizData.EachQuiz.length);
